### ISSUE TITLE
Changes to nvidia-docker packaging

### ISSUE THREAD

**Issue by kiendang** [kiendang/aur-nvidia-container-runtime#3]
There are major changes to `nvidia-docker` packaging starting with `docker` v19.03. See <https://github.com/NVIDIA/nvidia-container-runtime/releases/tag/3.1.0> and <https://github.com/NVIDIA/nvidia-docker>.

This is the current package hierarchy:
```yaml
nvidia-docker2:
  - nvidia-container-runtime:
     - nvidia-container-runtime-hook:
        - libnvidia-container-tools:
           - libnvidia-container
```

This is the new one:
```yaml
nvidia-container-toolkit:
  - libnvidia-container-tools:
    - libnvidia-container
```

`nvidia-container-toolkit` is basically just a new name for `nvidia-container-runtime-hook`.

In order to use docker with nvidia, user now installs `nvidia-container-toolkit` instead of `nvidia-docker`. `nvidia-container-runtime` still exists as a separate package which depends on `nvidia-container-toolkit`, but I'm not sure what its role is.

@jshap70
